FROM node:22-alpine AS build

WORKDIR /apps/web

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build


FROM nginx:alpine

COPY --from=build /apps/web/dist /usr/share/nginx/html

EXPOSE 80